SkuSearch.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SkuSearch.DataAccess;
using SkuSearch.Web.Models;

namespace SkuSearch.Web.Controllers
{
    public class HomeController : Controller
    {
        SkuSearchDBEntities db = new SkuSearchDBEntities();

        public ActionResult Index()
        {
            var freshProducts = (from fp in (
                                            from  tp in db.MultilanguageProperty
                                            where tp.WorldLanguageRef == "EN"
                                            select tp)                                
                                    where fp.MultilanguagePropertyProductDescription != null                                
                                    select fp).Take(10);
            var products = from pr in db.Product
                           select pr;
            var tuple = new Tuple<IEnumerable<SkuSearch.DataAccess.MultilanguageProperty>, IEnumerable<SkuSearch.DataAccess.Product>>(freshProducts, products);

            return View(tuple);            
        }

        [HttpPost]
        public ActionResult StoreLocator(string address)
        {
            // Make sure we have an address
            if (string.IsNullOrEmpty(address))
                return View();

            var results = GoogleMapsAPIHelpersCS.GetGeocodingSearchResults(address);

            var resultCount = results.Elements("result").Count();

            if (resultCount == 0)
            {
                // No matching address found!
                ViewData["No Results"] = true;
                return View();
            }
            else if (resultCount == 1)
            {
                // Got back exactly one result, show it!
                return RedirectToAction("StoreLocatorResults", new { Address = results.Element("result").Element("formatted_address").Value });
            }
            else
            {
                // Got back multiple results - We need to ask the user which address they mean to use...
                var matches = from result in results.Elements("result")
                              let formatted_address = result.Element("formatted_address").Value
                              select formatted_address;

                ViewData["Matches"] = matches;
                return View();
            }
        }
    }
}

SkuSearch.Web/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SkuSearch.DataAccess;


namespace SkuSearch.Web.Controllers
{
    public class SearchController : Controller
    {
        SkuSearchDBEntities db = new SkuSearchDBEntities();

        //
        // GET: /Search/
        public ActionResult Index()
        { 
            return View();
        }         

        //
        // GET: /Search/Browse?category=Apparel
        public ActionResult Browse(int id = 0)
        {

            var specificProducts = (from p in db.Product
                                   where p.CategoryRef == id
                                   select p);

            var productProperties = (from pp in db.MultilanguageProperty                                     
                                    select pp);

            var tuple = new Tuple<IEnumerable<SkuSearch.DataAccess.MultilanguageProperty>, IEnumerable<SkuSearch.DataAccess.Product>>(productProperties, specificProducts);

            return View(tuple);    
        }

        //
        // GET: /Search/Details/5
        public ActionResult Details (int id)
        {
            var detailedProduct = from dp in
                                      (
                                          from translatedProduct in db.MultilanguageProperty
                                          where translatedProduct.WorldLanguageRef == "EN"
                                          select translatedProduct).DefaultIfEmpty()
                                  where dp.MultilanguagePropertyID == id
                                  select dp;

            var originalProduct = from op in db.Product
                                  where op.ProductID == detailedProduct.FirstOrDefault().ProductRef
                                  select op;

            var tuple = new Tuple<IEnumerable<SkuSearch.DataAccess.MultilanguageProperty>, IEnumerable<SkuSearch.DataAccess.Product>>(detailedProduct, originalProduct);
 
            return View(tuple);
        }
        
        //
        //GET: /Search/CategoryMenu
        [ChildActionOnly]
        public ActionResult CategoryMenu()
        {
            var categories = db.Category.ToList();
            return PartialView(categories);
        }

        [ChildActionOnly]
        public ActionResult SearchingTextbox(string searchString)
        {
            // Searching by description
            var searchingProducts = from sp in db.MultilanguageProperty
                                    where sp.MultilanguagePropertyProductDescription.Contains(searchString)
                                    select sp;
            var originalProducts = from op in db.Product                                  
                                   select op;

            // Searching by name
            if (!searchingProducts.Any())
            {
                searchingProducts = from sp in db.MultilanguageProperty
                                    where sp.MultilanguagePropertyProductName.Contains(searchString)
                                    select sp;
            }

            if (searchString == null)
            {
                searchingProducts = from sp in db.MultilanguageProperty                                    
                                    select sp;
            }
            
            
            var tuple = new Tuple<IEnumerable<SkuSearch.DataAccess.MultilanguageProperty>, IEnumerable<SkuSearch.DataAccess.Product>>(searchingProducts, originalProducts);
            return  PartialView(tuple);

        }       
    }
}

SkuSearch.Web/Controllers/StockLocationsController.cs
using SkuSearch.DataAccess;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SkuSearch.Web.ViewModels;

namespace SkuSearch.Web.Controllers
{
    public class StockLocationsController : Controller
    {
        SkuSearchDBEntities db = new SkuSearchDBEntities();
        //
        // GET: /StockLocations/

        public ActionResult Index(decimal Latitude, decimal Longitude)
        {
            //get ids of products located in the nearby stocks 
            var _productIds = (from sa in db.StockLocation.AsEnumerable()
                             where (Math.Abs((float)(sa.StockLocationLatitude - Latitude)) < 0.25 && Math.Abs((float)(sa.StockLocationLongitude - Longitude)) < 0.25)
                             join ps in db.ProductStorage
                             on sa.StockLocationID equals ps.StockLocationRef
                             let dist = Math.Sqrt(Convert.ToDouble((sa.StockLocationLatitude - Latitude) * (sa.StockLocationLatitude - Latitude) + (sa.StockLocationLongitude - Longitude) * (sa.StockLocationLongitude - Longitude)))
                             orderby dist
                             select ps.ProductRef).ToList();

            //get nearby stocks 
            var _searchingAddress = (from sa in db.StockLocation.AsEnumerable()
                                     where (Math.Abs((float)(sa.StockLocationLatitude - Latitude)) < 0.25 && Math.Abs((float)(sa.StockLocationLongitude - Longitude)) < 0.25)
                                     let dist = Math.Sqrt(Convert.ToDouble((sa.StockLocationLatitude - Latitude) * (sa.StockLocationLatitude - Latitude) + (sa.StockLocationLongitude - Longitude) * (sa.StockLocationLongitude - Longitude)))
                                     orderby dist
                                     select sa).ToList();

            //get ids of nearby stocks
            var _stockIds = (from sa in db.StockLocation.AsEnumerable()
                                     where (Math.Abs((float)(sa.StockLocationLatitude - Latitude)) < 0.25 && Math.Abs((float)(sa.StockLocationLongitude - Longitude)) < 0.25)
                                     let dist = Math.Sqrt(Convert.ToDouble((sa.StockLocationLatitude - Latitude) * (sa.StockLocationLatitude - Latitude) + (sa.StockLocationLongitude - Longitude) * (sa.StockLocationLongitude - Longitude)))
                                     orderby dist
                                     select sa.StockLocationID).ToList();

            //get appropriate productStorages
            var _storage = (from prodStorage in db.ProductStorage
                            where _productIds.Contains(prodStorage.ProductRef) && _stockIds.Contains(prodStorage.StockLocationRef)
                            select prodStorage).ToList();

            //get ids of nearby stocks with repeatings (not sorted)
            List<int> searchingStocks = new List<int>();

            foreach (var storage in _storage)
            {
                searchingStocks.Add(storage.StockLocationRef);
            }

            //get nearby stocks with repeatings (sorted by distance)
            List<SkuSearch.DataAccess.StockLocation> _searchingStockProperties = new List<StockLocation>();

            foreach (var stock in _searchingAddress)
            {
                foreach (var stockId in searchingStocks)
                {
                    if (stockId == stock.StockLocationID)
                    {
                        _searchingStockProperties.Add(stock);
                    }
                }                
            }
            
            
            //get all product names 
            var allProducts = (from products in db.MultilanguageProperty 
                               where products.WorldLanguageRef == "EN"                                      
                                    select products).ToList();            

            //get product properties searched by user
            List<SkuSearch.DataAccess.MultilanguageProperty> _searchingProducts = new List<MultilanguageProperty>();

            foreach (var prodId in _productIds)
            {
                foreach (var prodName in allProducts)
                {
                    
                        if (prodId == prodName.ProductRef)
                        {
                            _searchingProducts.Add(prodName);
                        }                   
                }
            }          

            //get distance from stocks to the address set by user
            List<double> distancesWithRepeatings = new List<double>();

            foreach (var searchingStock in _searchingStockProperties)
            {
                distancesWithRepeatings.Add(Math.Sqrt(Convert.ToDouble((searchingStock.StockLocationLatitude - Latitude) * (searchingStock.StockLocationLatitude - Latitude) + (searchingStock.StockLocationLongitude - Longitude) * (searchingStock.StockLocationLongitude - Longitude))));
            }            
            
            //get original products (for images)
            List<SkuSearch.DataAccess.Product> _originalProducts = new List<SkuSearch.DataAccess.Product>();

            foreach (var prodId in _productIds)
            {
                foreach (var orignalProd in db.Product)
                {
                    if (prodId == orignalProd.ProductID)
                    {
                        _originalProducts.Add(orignalProd);
                    }
                }
            }
            
            StockLocationsViewModel model = new StockLocationsViewModel
            {
                searchingProducts = _searchingProducts,
                distance = distancesWithRepeatings,
                searchingAddress = _searchingStockProperties,
                originalProducts = _originalProducts,
                productStorages = _storage
            };

            return View(model);
        }

    }
}

SkuSearch.Web/Views/Home/Index.cshtml
@model Tuple<IEnumerable<SkuSearch.DataAccess.MultilanguageProperty>, IEnumerable<SkuSearch.DataAccess.Product>>

@helper Truncate(string input, int length)
{
    if (input.Length <= length) 
    { 
        @input
    } 
    else 
    { 
        @input.Substring(0, length)<text>...</text>
    }
}

<body class="metro">
    
    @{
        ViewBag.Title = "Home";
    }        

     @{
        Layout = "~/Views/Shared/_LayoutPage1.cshtml";        
      } 
    

    <h2 style="margin-left: 20px;"><b>Sku4You </b><sup>beta</sup></h2>

    <div style="margin-left: 10px; width: 100%; display:inline-block">
    
        <div style= "float: right; margin-right: 50px; margin-top: 70px;">
                        <h1 style="width: 50%; margin: auto;">Freshly added</h1>
                          <div id="product-list-container">                                
                              <ul id="product-list">
                                @foreach (var product in Model.Item1)
                                {                                      
                                    <li>
                                    @foreach (var originalProduct in Model.Item2) 
                                    {                                        
                                        if (originalProduct.ProductID == product.ProductRef)
                                        {
                                            if (originalProduct.ProductImage != null)
                                            { 
                                              <div id="image-list-container">
                                                  <a title="@product.MultilanguagePropertyProductName" href="@Url.Action("Details", "Search", new { id = product.ProductRef })">
                                                        <img src="@Url.Content("/Content2/images/"+originalProduct.ProductImage)"/></a>                                                        
                                                  </div>
                                                
                                            }
                                            else
                                            {
                                               <div id="image-list-container">
                                                       <a title="@product.MultilanguagePropertyProductName" href="@Url.Action("Details", "Search", new { id = product.ProductRef })">
                                                        <img src="@Url.Content("~/Content2/images/cart_product_default.png")"/></a>                                                                                                       
                                                </div>
                                            }                     
                                        }
                                    }
                                       @Html.ActionLink(Truncate(product.MultilanguagePropertyProductName, 30).ToString(), "Details", "Search", new { id = product.ProductRef }, new { title = @product.MultilanguagePropertyProductName})                                        

                                  </li>
                                }
                            </ul>
                                  
                          </div>
                    </div>
            <p id="demo">Click the button to get your coordinates:</p>

        <button onclick="getLocation()">Get Location</button>

        <script>
            var x = document.getElementById("demo");

            function getLocation() {
                if (navigator.geolocation) {
                    navigator.geolocation.getCurrentPosition(showPosition);
                } else {
                    x.innerHTML = "Geolocation is not supported by this browser.";
                }
            }

            function showPosition(position) {
                var textBox = document.getElementById("addressBox")
                x.innerHTML = "Your location: " + '<input type="Text" id="locationBox" value="' + position.coords.latitude + "," + position.coords.longitude + '">';
                var location = position.coords.latitude + "," + position.coords.longitude;

            }
        </script>

        @*Use the Google Geocoding service to get information about the user-entered address*@
       

            <div style= "width:auto; margin-left: 50px;">
                 <h2>Map an Address</h2>
            <form method="post">
                <fieldset>
                  <div>
                    <label for="address">Address:</label>
                    <input style="width: 328px" type="text" name="addressBox" value="@Request["addressBox"]" />
                    <input type="submit" onclick="showPosition" value="Map It!" />
                   </div>
                </fieldset>
            </form>
                
                
    
      @{var url = String.Format("http://maps.google.com/maps/api/geocode/xml?address={0}&sensor=false", Server.UrlEncode(Request.Form["addressBox"]));

        // Load the XML into an XElement object
        var results = System.Xml.Linq.XElement.Load(url);
        // Determine how many elements exist
        var resultCount = results.Elements("result").Count();  
        // How many results did we get back?
        if (resultCount == 0)
        {
            <h>Cannot find matches</h>
        }
        //else if (resultCount == 1)
        //{
        //    // Send the user to the results page
        //    Server.Transfer(
        //}         
        
        else if (resultCount >= 1)
        {                   
            //Multiple results
            var matches = from result in results.Elements("result")
                          let formatted_address = result.Element("formatted_address").Value
                          select formatted_address;

            <table class="content-wrapper">
                Did you mean
                @foreach (var item in matches)
                {
                <tr>                    
                    <th>
                         @Html.ActionLink(item, "Index", "StockLocations", new { latitude = results.Element("result").Element("geometry").Element("location").Element("lat").Value, longitude = results.Element("result").Element("geometry").Element("location").Element("lng").Value, myGeolocation = results.Element("result").Element("formatted_address").Value}, null)
                    </th>
                </tr>
                }
            </table>
        }
         
          
        }
            <div style="margin-top:10px">
                @Maps.GetGoogleHtml(Request.Form["addressBox"],
                        width: "400",
                        height: "400"
                        ); 
                </div>        
            </div>

             
    </div>

   
    <div id="FooterWrapper">
			<div id="Footer">
				Sku4You © 2014 Inherent Simplicity Baltic. All rights reserved.
			</div>
		</div>
</body>